todo-config-server:
  homeScreen : Home Screen
  titleMissing: Title is missing
  todoItemNotFound: Todo item is not found
  userNotFound: User not found
  fetchAllUser: Fetch users successfully
  fetchUser: Fetch user successfully
  userCreated: User created successfully
  todoDeleted: Todo deleted successfully
